kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - npm install
  - npx parcel build src/index.html

- name: clean-server
  image: appleboy/drone-ssh
  settings:
  host: 10.1.0.40
  username: www-deploy
  password:
    from_secret: webserver-ssh-deploy-password
  script:
  - rm -rf /var/www/yshep.io/*
  when:
    branch:
    - main
    event:
    - push
    - tag

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 10.1.0.40
    username: www-deploy
    password:
      from_secret: webserver-ssh-deploy-password
    target: /var/www/yshep.io/
    source:
    - dist/*
    strip_components: 1
    overwrite: true
  when:
    branch:
    - main
    event:
    - push
    - tag
